"""
extract_features_ravdess.py

Extracts Multilingual BERT (text) + emotion2vec (audio) features from
RAVDESS (Common-6) and saves them as .pkl files, exactly like the other
dataset extraction scripts.

Run AFTER process_ravdess.py has generated the CSVs.

Output: features_common_6/RAVDESS_Common6_{train|val|test}.pkl
"""
import warnings
warnings.filterwarnings('ignore')

import os
import torch
import pickle
import numpy as np
import pandas as pd
from transformers import BertTokenizer, BertModel
from funasr import AutoModel

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
TEXT_MAX_LENGTH = 100

# ── INPUT PATHS (generated by process_ravdess.py) ─────────────────────────────
RAVDESS_TRAIN_PATH = "/dist_home/suryansh/sharukesh/speech/metadata/RAVDESS_Common6_train.csv"
RAVDESS_VAL_PATH   = "/dist_home/suryansh/sharukesh/speech/metadata/RAVDESS_Common6_val.csv"
RAVDESS_TEST_PATH  = "/dist_home/suryansh/sharukesh/speech/metadata/RAVDESS_Common6_test.csv"

OUTPUT_PATH = "/dist_home/suryansh/sharukesh/speech/features_common_6/"
os.makedirs(OUTPUT_PATH, exist_ok=True)

# ── LOAD MODELS ───────────────────────────────────────────────────────────────
# Multilingual BERT — same model as IEMOCAP/EmoDB/EMOVO so all datasets share
# one embedding space. RAVDESS is English, which mBERT handles natively.
print("Loading Multilingual BERT...")
tokenizer  = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
text_model = BertModel.from_pretrained(
    'bert-base-multilingual-cased', use_safetensors=True
).to(device)

# emotion2vec — same model used for all other datasets
print("Loading emotion2vec...")
emotion2vec_model = AutoModel(model="iic/emotion2vec_plus_large", model_revision="v2.0.5")

print("Models loaded.\n")


def extract_emotion2vec_features(audio_path):
    """
    Passes the preprocessed 16 kHz mono WAV through emotion2vec_plus_large.
    Returns a float tensor of shape [D] (utterance-level feature), or None on error.
    """
    try:
        result = emotion2vec_model.generate(audio_path, output_dir=None, granularity="utterance")
        if isinstance(result, list) and len(result) > 0:
            feats = result[0].get('feats', None)
            if feats is not None:
                if isinstance(feats, np.ndarray):
                    return torch.from_numpy(feats).float()
                return feats.float()
        return None
    except Exception as e:
        print(f"  Error in emotion2vec for {audio_path}: {e}")
        return None


def process_dataset(dataset_path, output_file):
    """
    Reads a CSV, extracts mBERT + emotion2vec features for each sample,
    and saves the list of dicts as a pickle file.

    Each dict contains:
        text_embed  : torch.Tensor [768]  — CLS token from mBERT
        audio_embed : torch.Tensor [D]    — utterance embedding from emotion2vec
        label       : torch.Tensor (int)  — Common-6 label (0–5)
        speaker_id  : str                 — e.g. "Actor_01"
    """
    if not os.path.exists(dataset_path):
        print(f"Skipping {dataset_path} (not found — run process_ravdess.py first)")
        return

    dataset = pd.read_csv(dataset_path)
    processed_data = []
    failed = 0

    print(f"Processing {len(dataset)} samples from {dataset_path}...")

    with torch.no_grad():
        for idx in range(len(dataset)):
            if idx % 50 == 0:
                print(f"  Progress: {idx}/{len(dataset)}")

            try:
                # ── TEXT: Multilingual BERT CLS embedding ──────────────────
                text = str(dataset['raw_text'][idx])
                text_token = tokenizer(
                    text,
                    return_tensors="pt",
                    truncation=True,
                    max_length=TEXT_MAX_LENGTH,
                    padding="max_length"
                ).to(device)
                text_embed = text_model(**text_token).last_hidden_state[:, 0, :][0].cpu()

                # ── AUDIO: emotion2vec utterance embedding ─────────────────
                audio_file = dataset['audio_file'][idx]
                audio_embed = extract_emotion2vec_features(audio_file)
                if audio_embed is None:
                    print(f"  Failed audio at idx {idx}: {audio_file}")
                    failed += 1
                    continue

                # ── LABEL: already mapped to 0-5 by process_ravdess.py ─────
                label = torch.tensor(int(dataset['label'][idx]))

                processed_data.append({
                    'text_embed':  text_embed,
                    'audio_embed': audio_embed,
                    'label':       label,
                    'speaker_id':  dataset['speaker_id'][idx],
                })

            except Exception as e:
                print(f"  Error at idx {idx}: {e}")
                failed += 1

    print(f"  Done: {len(processed_data)} saved, {failed} failed.")

    with open(output_file, "wb") as f:
        pickle.dump(processed_data, f)
    print(f"  Saved → {output_file}\n")


def main():
    process_dataset(RAVDESS_TRAIN_PATH, f"{OUTPUT_PATH}RAVDESS_Common6_train.pkl")
    process_dataset(RAVDESS_VAL_PATH,   f"{OUTPUT_PATH}RAVDESS_Common6_val.pkl")
    process_dataset(RAVDESS_TEST_PATH,  f"{OUTPUT_PATH}RAVDESS_Common6_test.pkl")


if __name__ == "__main__":
    main()
